# render.yaml
# Render.com Python environment version for YouTube Downloader Telegram Bot

services:
  - type: web
    name: ytbot
    runtime: python
    region: oregon
    plan: free
    autoDeploy: true
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: CHANNEL_ID
        sync: false
      - key: WEBHOOK_BASE
        sync: false
      - key: SECRET_PATH
        value: "/webhook"
